---
title: "NIST_1.3"
author: "Sakaguchi"
date: "2025-07-10"
output: html_document

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(flextable)

knitr::opts_chunk$set(echo = TRUE)

```

# [EDA Techniques](https://www.itl.nist.gov/div898/handbook/eda/section3/eda3.htm)

- **Summary**
  - データセットを収集後、探索的データ解析をどのように進めるか?
  - あまたある技術の何に焦点を当てたらよいか?
  - 期待するのはどのような結論か?
  
  - 本章
    - EDA技術紹介を通してこれらの疑問に答え
    - 各技術の詳細を記述
    - グラフィカル、定量的な技術の両方に触れる
    - EDAでは主にグラフ技法に重点

- **第3章の目次**
   1. [導入](https://www.itl.nist.gov/div898/handbook/eda/section3/eda31.htm)
   2. [分析の議題](https://www.itl.nist.gov/div898/handbook/eda/section3/eda32.htm)
   3. [グラフ技術: アルファベット順](https://www.itl.nist.gov/div898/handbook/eda/section3/eda33.htm)
   4. [グラフ化技術: 課題分類](https://www.itl.nist.gov/div898/handbook/eda/section3/eda34.htm)
   5. [定量手法: アルファベット順](https://www.itl.nist.gov/div898/handbook/eda/section3/eda35.htm)
   6. [確率分布](https://www.itl.nist.gov/div898/handbook/eda/section3/eda36.htm)


## [1.3.1. Introduction](https://www.itl.nist.gov/div898/handbook/eda/section3/eda31.htm)

- **グラフィカルと定量的手法**
  - 多くの探索的、古典的データ分析の技法を紹介していく章
  - 網羅的なリストではない
  - その他ある技法は他の章で述べられる
  - 具体例
    - [製品比較](https://www.itl.nist.gov/div898/handbook/prc/prc.htm)では古典的統計手法の多くを紹介
  
  - EDAはグラフ技法に重点をおき、古典的技法は定量手法に置く
  - 実践上は、グラフと定量技法を併せて使用
  - 本章では、グラフ、定量的技法の記述に分けて説明
    - 分類分けを明確にする為の区分け
    - データ分析の際、グラフ、定量的技法の併用を進めないということではない

- **ケーススタディで使用する技法**
  - 本章は、技法そのものに重点を置く
    - グラフ、検定の定義、公表された参考文献、出力例について
    - 技法の使用と質問への解答はケーススタディにて
      - ケーススタディですべての技術が示されるわけではない

- **利用可能なソフトウエア**
  - (NISTサイトはDataplotとR)
    - Rと出来ればPythonも将来的に補完していきたい


## [1.3.2. Analysis Questions](https://www.itl.nist.gov/div898/handbook/eda/section3/eda32.htm)

- **EDA議題**
  - 
  

