---
title: "NIST_1.2"
author: "Sakaguchi"
date: "2025-05-02"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(gridExtra)
library(flextable)

knitr::opts_chunk$set(echo = TRUE)

```

# EDA Assumptions
- **Summary**
- 科学的工学的実験の範囲は事実上無限
- 体系的かつ妥当性あり、裏付けと再現性のある研究結果を導出可能な基盤はあるのか?
- そのような基礎がある
  - 複雑な測定プロセスでもその根底には一定の前提ありという事実に根差す
  - このセクションで議論すること
    - そのような仮定は何か?
    - なぜ重要か?
    - どのように仮定を検定するのか?
    - 成立しない場合はどのような結果になるのか?
    
― **Section2のコンテンツ**
   1. 根底にある仮定
   2. 重要事項
   3. 検定における前提
   4. プロットの重要性
   5. 結果

## [1.2.1. Underlying Assumptions](https://www.itl.nist.gov/div898/handbook/eda/section2/eda21.htm)

- **測定プロセスに係る仮定**
- すべての測定プロセスで得られるデータのふるまいとして仮定されること
   1. 無作為抽出
   2. 固定の分布からなること
   3. 位置固定の分布を持つ
   4. 固定変動の分布を持つ

- **「位置固定」**の異なるタイプの問題
  - 最も単純な[単変数]タイプ
    - response = deterministic component + random component
    - becomes
      - response = constant + error

- **単変数モデルにおける仮定**
- このケースの「固定位置」は単純に未知の定数のこと
- 以下のような特性を持つデータを生成する一定の条件があると想定できる
  - あるデータは他のデータと相関はない
  - ランダムな成分は固定の分布を有する
  - 決定的成分は定数
  - ランダム成分は固定の変動

- **多変数系への拡張**
- 単変数モデルの普遍的な検定力、重要性
  - 決定論的要素が多変数関数であるより一般的なモデルに容易に拡張可能
- 残差のふるまい
  - 実際の応答と**フィットした**モデルによる予測値の差は単変数プロセスと同様のふるまい(重要)
   1. 無作為抽出
   2. 固定の分布からなること
   3. 位置固定の分布を持つ
   4. 固定変動の分布を持つ

- フィットしたモデルから得られる残差の挙動を検定
  - もし上記の条件が成立しない
    - 選択したモデルが不適で改良の必要あり

## [1.2.2. Importance](https://www.itl.nist.gov/div898/handbook/eda/section2/eda22.htm)

- **予測可能性と統計的管理**
- 予測可能性
  - 科学・エンジニアリングにおける重要な目標
  - 4つの仮定が成り立つなら、確率的予測可能性を達成と言える
    - 過去だけでなく未来のプロセスも見通せる
      - [**統計的管理**]{style="color: red"}

- **エンジニアリング上の結論における妥当性**
- 4つの仮定が当てはまる場合
  - プロセスは科学的・エンジニアリング的に妥当な結論を得る
- 4つの仮定が当てはまらない場合
  - 

